image: danbla/fuglutestenv

stages:
  - build
  - test_isolated
  - test
  - build_py3
  - test_py3_isolated
  - test_py3

unittests:
  stage: test
  script:
    - cd fuglu
    - nosetests --rednose tests/unit
  only:
    - master
    - develop
    - suspectatt

isolated:
  stage: test_isolated
  script:
    - cd fuglu
    - nosetests --rednose tests/isolated --with-isolation
  only:
    - master
    - develop
    - suspectatt

unittests_py3:
  stage: test_py3
  script:
    - cd fuglu
    - nosetests-3.4 --rednose tests/unit
  only:
    - master
    - develop
    - suspectatt

isolated_py3:
  stage: test_py3_isolated
  script:
    - cd fuglu
    - nosetests-3.4 --rednose tests/isolated  --with-isolation
  only:
    - master
    - develop
    - suspectatt

integrationtests:
  stage: test
  script:
    - /usr/local/bin/start-services.sh
    - cd fuglu
    - nosetests --rednose tests/integration
  only:
    - master
    - develop
    - suspectatt

integrationtests_py3:
  stage: test_py3
  script:
    - /usr/local/bin/start-services.sh
    - cd fuglu
    - nosetests-3.4 --rednose tests/integration
  only:
    - master
    - develop
    - suspectatt


# define RSYNC_TARGET in gitlab -> project domainmagic -> settings -> variables

buildfuglu:
  stage: build
  script:
    - cd fuglu 
    - python setup.py build_py -d /tmp/build install --force
    - rename '.dist' '' /etc/fuglu/*.dist
    - mkdir -p /var/log/fuglu
    - chown nobody /var/log/fuglu
  only:
    - master
    - develop
    - suspectatt


buildfuglu_py3:
  stage: build_py3
  script:
    - cd fuglu
    - python3 setup.py build_py -d /tmp/build install --force
    - rename '.dist' '' /etc/fuglu/*.dist
    - mkdir -p /var/log/fuglu
    - chown nobody /var/log/fuglu
  only:
    - master
    - develop
    - suspectatt
